version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch"
      - "discovery.zen.ping.unicast.hosts=elasticsearch2,elasticsearch3,elasticsearch4,elasticsearch5"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch-client.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - node.name=es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch2"
      - "discovery.zen.ping.unicast.hosts=elasticsearch,elasticsearch3,elasticsearch4,elasticsearch5"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - node.name=es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch3"
      - "discovery.zen.ping.unicast.hosts=elasticsearch,elasticsearch2,elasticsearch4,elasticsearch5"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch4:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch4
    environment:
      - cluster.name=docker-cluster
      - node.name=es4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch4"
      - "discovery.zen.ping.unicast.hosts=elasticsearch,elasticsearch2,elasticsearch3,elasticsearch5"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata4:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch5:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch5
    environment:
      - cluster.name=docker-cluster
      - node.name=es5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch5"
      - "discovery.zen.ping.unicast.hosts=elasticsearch,elasticsearch2,elasticsearch3,elasticsearch4"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata5:/usr/share/elasticsearch/data
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local
  esdata5:
    driver: local

networks:
  esnet:
