version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: es-client1
    environment:
      - cluster.name=docker-cluster
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch"
      - "discovery.zen.ping.unicast.hosts=es-master1,es-master2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch-client.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: elasticsearch:6.6.2
    container_name: es-master1
    environment:
      - cluster.name=docker-cluster
      - node.name=es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch2"
      - "discovery.zen.ping.unicast.hosts=es-master2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch3:
    image: elasticsearch:6.6.2
    container_name: es-data1
    environment:
      - cluster.name=docker-cluster
      - node.name=es3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch3"
      - "discovery.zen.ping.unicast.hosts=es-master1,es-master2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch4:
    image: elasticsearch:6.6.2
    container_name: es-data2
    environment:
      - cluster.name=docker-cluster
      - node.name=es4
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch4"
      - "discovery.zen.ping.unicast.hosts=es-master1,es-master2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata4:/usr/share/elasticsearch/data
      - ./elasticsearch-data.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  elasticsearch5:
    image: elasticsearch:6.6.2
    container_name: es-master2
    environment:
      - cluster.name=docker-cluster
      - node.name=es5
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.http.cname_in_publish_address=true"
      - "network.host=elasticsearch5"
      - "discovery.zen.ping.unicast.hosts=es-master1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata5:/usr/share/elasticsearch/data
      - ./elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - esnet
  kibana:
    image: kibana:6.6.2
    container_name: kibana
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - esnet
  logstash:
    image: logstash:6.6.2
    container_name: logstash
    volumes:
      - ./config:/usr/share/logstash/pipeline
    ports:
      - 6666:6666
    networks:
      - esnet

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local
  esdata5:
    driver: local

networks:
  esnet:
